BEGIN;

CREATE TYPE ROLE AS ENUM ('member', 'admin', 'manager');

CREATE TABLE IF NOT EXISTS USERS
(
  ID    SERIAL                  NOT NULL CONSTRAINT USERS_PKEY PRIMARY KEY,
  EMAIL VARCHAR(255) DEFAULT '' NOT NULL CHECK (EMAIL <> '') CONSTRAINT USERS_EMAIL UNIQUE,
  NAME  VARCHAR(255) DEFAULT '' NOT NULL CHECK (NAME <> ''),
  ROLE  ROLE                    NOT NULL DEFAULT 'member'
);

COMMIT;
